services:
  postgres:
    image: postgres:15
    container_name: taskmanager-postgres
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: taskmanager-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - task-manager-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: taskmanager-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: taskmanager
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: 9My5uperSecretKey***GoesHere***ItShoultBe1ong3nough!
      JWT_EXPIRES_IN: 7d
      NODE_ENV: development
    networks:
      - task-manager-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


volumes:
  postgres_data:
  redis_data:

networks:
  task-manager-network:
    driver: bridge

